core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
   
    #Dashboard
    path('', include('dashboard.urls', namespace='dashboard')),

    #Frontend
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from dashboard.users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.urls import path


from dashboard import dashboard_views
from dashboard.users import users_views

app_name='dashboard'

urlpatterns = [
    
    path('conf/',dashboard_views.conf, name="conf"),
    path('setting/',dashboard_views.setting, name="setting"),
    path('comms/',dashboard_views.comms, name="comms"),
    

    path('employees/',dashboard_views.employees, name="employees"),
    path('employees/export/',dashboard_views.export_employees, name="export_employees"),

    path('employees/old/', dashboard_views.employeesold, name="old"),

    path('employee/<int:id>/delete/', dashboard_views.deleteemployee, name="deleteemployee"), 
    path('employee/<int:id>/edit/', dashboard_views.editemployee, name="editemployee"),
    path('employee/<int:id>/comms/', dashboard_views.employee_comms, name="employee_comms"),

    
    path('holiday/delete/<int:id>/', dashboard_views.deleteholiday, name="deleteholiday"), 
    path('holiday/edit/<int:id>/', dashboard_views.editholiday, name="editholiday"), 



    path('ceo/',dashboard_views.ceo, name="ceo"),
    path('ceo/edit/<int:id>/', dashboard_views.editceo, name="editceo"),  
    path('ceo/delete/<int:id>/', dashboard_views.deleteceo, name="deleteceo"),  
    path('ceo/export/', dashboard_views.export_ceo, name="export_ceo"),  

    path('expenses/', dashboard_views.expenses, name="expenses"),
    path('expenses/delete/<int:id>/', dashboard_views.deleteexpense, name="deleteexpense"), 
    path('expenses/edit/<int:id>/', dashboard_views.editexpense, name="editexpense"), 
    path('expenses/deleteexpenses/', dashboard_views.delete_expenses, name="deleteexpenses"),
    path('expenses/history/<int:id>/', dashboard_views.expenseshistory, name="expenseshistory"),
    path('expenses/export/', dashboard_views.export_expenses, name="export_expenses"),

    
    path('clients/',dashboard_views.clients, name="clients"),
    path('clients/deleteclient/<int:id>/', dashboard_views.deleteclient, name="deleteclient"),
    path('clients/editclient/<int:id>/', dashboard_views.editclient, name="editclient"),
    path('clients/addclientsale/<int:id>/', dashboard_views.addclientsale, name="addclientsale"),
    path('clients/deleteclients/', dashboard_views.delete_clients, name="deleteclients"),
    path('clients/export/', dashboard_views.export_clients, name="export_clients"),
    path('clients/rr/export/', dashboard_views.export_rr, name="export_rr"),

    path('client-autocomplete/', dashboard_views.client_autocomplete, name='client_autocomplete'),

    path('adjustments/',dashboard_views.adjustment, name="adjustment"),
    path('adjustments/<int:id>/',dashboard_views.adjustment, name="adjustsale"),
    path('adjustment/<int:id>/delete/', dashboard_views.deleteadj, name="canceladj"),
    path('adjustment/<int:id>/change/', dashboard_views.editadj, name="editadj"),

    path('adj/',dashboard_views.adj, name="adj"),


    path('services/<int:id>/', dashboard_views.editservice, name="editservice"),
    path('services/<int:id>/restore/', dashboard_views.restoreservice, name="restoreservice"),




    path('cancellations/', dashboard_views.cancellations, name="cancellations"),




    path('sales/',dashboard_views.sales, name="sales"),
    path('sales/deletesale/<int:id>/', dashboard_views.deletesale, name="deletesale"),
    path('sales/editsale/<int:id>/', dashboard_views.editsale, name="editsale"),
    path('salesdata/',dashboard_views.salesdata, name="salesdata"),
    path('sales/deletesales/', dashboard_views.delete_sales, name="deletesales"),
    path('sales/export/', dashboard_views.export_sales, name='export_sales'),





    
	path('users/',users_views.users,name="users"),
	path('user-details/<int:id>/',users_views.user_details,name="user-details"),
	path('add-user/',users_views.add_user,name="add-user"),
	path('edit-user/<int:id>/',users_views.edit_user,name="edit-user"),
	path('delete-user/<int:id>/',users_views.delete_user,name="delete-user"),
	path('delete-multiple-user/',users_views.delete_multiple_user,name="delete-multiple-user"),

	path('login/',users_views.login_user,name="login"),
	path('logout/',users_views.logout_user,name="logout"),
	path('groups/',users_views.groups_list,name="groups"),
	path('group-edit/<int:id>/',users_views.group_edit,name="group-edit"),
	path('group-delete/<int:id>/',users_views.group_delete,name="group-delete"),
	path('group-add/',users_views.group_add,name="group-add"),
	path('permissions/',users_views.permissions,name="permissions"),
	path('edit-permissions/<int:id>/',users_views.edit_permissions,name="edit-permissions"),
	path('delete-permissions/<int:id>/',users_views.delete_permissions,name="delete-permissions"),
	path('assign-permissions-to-user/<int:id>/',users_views.assign_permissions_to_user,name="assign-permissions-to-user"),
	path('signup/',users_views.signup,name="signup"),
	path('activate/<uidb64>/<token>/',users_views.activate, name='activate'),


    path('',dashboard_views.index,name="index"),
    path('index/',dashboard_views.index,name="index"),
    path('activity/',dashboard_views.activity,name="activity"),
    path('page-lock-screen/',dashboard_views.page_lock_screen,name="page-lock-screen"),
    path('page-error-400/',dashboard_views.page_error_400,name="page-error-400"),
    path('page-error-403/',dashboard_views.page_error_403,name="page-error-403"),
    path('page-error-404/',dashboard_views.page_error_404,name="page-error-404"),
    path('page-error-500/',dashboard_views.page_error_500,name="page-error-500"),
    path('page-error-503/',dashboard_views.page_error_503,name="page-error-503"),


    path('', users_views.password_change, name='password_change'),






    # This Route for PasswordChange
    path('password/', users_views.password_change, name='password_change'),

    # These Routes for PasswordReset
    path('password_reset/', auth_views.PasswordResetView.as_view(
        form_class=EmailValidationOnForgotPassword,
        success_url=reverse_lazy('dashboard:password_reset_done')),name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('dashboard:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


] 

dashboard/users/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager 
from django.contrib.auth.models import Group




class CustomAccountManager(BaseUserManager):
	
	def create_superuser(self, email, username, first_name, last_name, password,**other_fields):
		other_fields.setdefault('is_staff',True)
		other_fields.setdefault('is_superuser',True)
		other_fields.setdefault('is_active',True)
		if other_fields.get('is_staff') is not True:
			raise ValueError(
				'Superuser must be assigned to is_staff=True.')
		if other_fields.get('is_superuser') is not True:
			raise ValueError(
				'Superuser must be assigned to is_superuser=True.')
		super_user = self.create_user(username,email,first_name, last_name, password, **other_fields)
		return super_user

	def create_user(self, username,email, first_name, last_name, password,**other_fields):
		if not email:
			raise ValueError(_('You must provide an email address'))
		email = self.normalize_email(email)
		user = self.model(username=username, email=email, first_name=first_name, last_name=last_name, **other_fields)
		user.set_password(password)
		user.save()
		return user


def user_directory_path(instance, filename):
	return f'users/{instance.email}/images/{filename}'

class CustomUser(AbstractBaseUser, PermissionsMixin):
	GENDER_CHOICES = (
		('','Choose gender'),
		('Male', 'Male'),
		('Female', 'Female'),
		('Others', 'Others'),
	)
	username = models.CharField(max_length=191,unique=True)
	email = models.EmailField(_('email address'),unique=True)
	first_name = models.CharField(max_length=255,blank=True)
	last_name = models.CharField(max_length=255,blank=True)
	groups = models.ManyToManyField(Group,blank=True)
	
	is_staff = models.BooleanField(default=True)
	is_active = models.BooleanField(default=True)
	
	objects = CustomAccountManager()

	USERNAME_FIELD = 'email'  
	REQUIRED_FIELDS = ['username','first_name','last_name']
	

	def __str__(self):
		return self.username

dashboard/forms.py
from django import forms
from django.forms import ModelForm, TextInput

from dashboard.models import Configurations, Comms, ConfTier

class TierConf(ModelForm):
    class Meta:
        model = ConfTier
        exclude = ['id', 'tier_v']
        
        widgets = {
            'tier_i' : TextInput(attrs={'class':"form-control",
            'id':"tier_i",
            'placeholder':"Tier I"}),
            
            'tier_ii' : TextInput(attrs={'class':"form-control",
            'id':"tier_ii",
            'placeholder':"Tier II"}),
            
            'tier_iii' : TextInput(attrs={'class':"form-control",
            'id':"tier_iii",
            'placeholder':"Tier III"}),
            
            'tier_iv' : TextInput(attrs={'class':"form-control",
            'id':"tier_iv",
            'placeholder':"Tier IV"}),
            
            
        }


class CommsForm(forms.ModelForm):
    class Meta:
        model = Comms
        exclude = ['id']
        
        widgets = {
            'rr_1' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_1",
            'placeholder':"RR I"}),
            
            'com_rr_1' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_1",
            'placeholder':"COMM RR I"}),
            
            'rr_2' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_2",
            'placeholder':"RR II"}),
            
            'com_rr_2' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_2",
            'placeholder':"COMM RR II"}),
            
            'rr_3' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_3",
            'placeholder':"RR III"}),
            
            'com_rr_3' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_3",
            'placeholder':"COMM III"}),
            
            'rr_4' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_4",
            'placeholder':"RR IV"}),
            
            'com_rr_4' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_4",
            'placeholder':"COMM RR IV"}),
            
            'rr_5' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_5",
            'placeholder':"RR V"}),
            
            'com_rr_5' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_5",
            'placeholder':"COMM RR V"}),
            
            'one_off' : forms.TextInput(attrs={'class':"form-control",
            'id':"one_off",
            'placeholder':"One Off"}),
            
            'up_sell' : forms.TextInput(attrs={'class':"form-control",
            'id':"up_sell",
            'placeholder':"Up Sell"}),         
            
        }

class UploadFileForm(forms.Form):
    file = forms.FileField()



class ConfigurationForm(forms.ModelForm):
    
    class Meta:
        model = Configurations
        fields = ( 
                  'name',
                  'value',
                  'title',
                  'description',
                  'input_type',
                  'editable',
                  'params'
                  )
                    

dashboard/users/forms.py
from django import forms
from dashboard.users.models import CustomUser
from django.contrib.auth.models import Group, Permission
from django.contrib.auth import authenticate
from django.contrib.auth.forms import PasswordResetForm


class SignupForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = CustomUser
        fields = (
                  'username',
                  'email',
                  'first_name',
                  'last_name',
                  'password1',
                  'password2',
                )
        
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


#Add User Form
class CustomUserForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(),required=False)


    class Meta:
        model = CustomUser
        fields = ( 
                  'username',
                  'email',
                  'first_name',
                  'last_name',
                  'groups',
                  'password1',
                  'password2',
                )
       
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user







class EditUserForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(),required=False)
   

    class Meta:
        model = CustomUser
        fields = (
                  'username',
                  'email',
                  'first_name',
                  'last_name',
                  
                  'groups',
                )

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save()
        return user




class LoginForm(forms.Form):
    email =  forms.EmailField()
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        return self.cleaned_data
        
    def login(self, request):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        return user
        

class EmailValidationOnForgotPassword(PasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        if not CustomUser.objects.filter(email__iexact=email, is_active=True).exists():
            raise forms.ValidationError("There is no user registered with the specified email address!")
        return email


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('name','permissions')

class PermissionsForm(forms.ModelForm):
    name = forms.CharField(label='Name', help_text="Example: Can action modelname")
    codename = forms.CharField(label='Code Name', help_text="Example: action_modelname")

    class Meta:
        model = Permission
        fields = ('name','codename','content_type')


class UserPermissionsForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('user_permissions',)

dashboard/templates/dashboard/employees/ceo.html
{% extends 'dashboard/elements/layouts/admin.html' %}

{% load static %}

{% block additional_css %}
{% endblock %}

{% block content %}



<!-- MAIN CEO -->
    

    <div class="row">     
        <div class="col-xl-12">
            

            <div class="card">

                <div class="card-header border-0 flex-wrap pb-0 mb-5">
                    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">NEW<span class="btn-icon-end">
                        <i class="fa fa-plus"></i></span> </button>
    
                        <a class="btn btn-info" href="{% url 'dashboard:export_ceo' %}">
                            Export CEO Info
                            <span class="btn-icon-end">
                                <i class="fa-solid fa-file-export"></i>
                            </span>
                        </a>    
                </div>

                
                <div class="card-body">
                    
                    <!-- TABLE EMPLOYEES -->
                    <div class="table-responsive py-4">
                        <table id="example4" class="display mb-4" style="min-width: 845px">
                            <thead>
                                <tr>
                                    
                                    <th>NAME</th>
                                    <th>SALARY</th>
                                    <th>MP</th>
                                    <th>TC</th>
                                   
                                    <th>ATM</th>
                                    <th>CASH $</th>
                                    <th>CASH USD</th>
                                    <th>PAYPAL</th>
                                    <th>MONTHLY BONUS </th>
                                    <th>TOTAL </th>


                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>{% if ceo %}
                                {% for employee in ceo %}
                                <tr>
                                    <td>
                                        <div class="d-flex align-items-center">
                                            <a class="mb-0 fs-16 font-w500" href="{% url 'dashboard:editceo' id=employee.id %}">{{employee.name}}</a>
                                        </div>
                                    </td>


                                    <td>${{employee.get_salary|floatformat:2|default_if_none:"0"}}</td>

                                    <td>${{employee.get_mp|floatformat:2|default_if_none:"0"}}</td>
                                    
                                    <td>${{employee.get_tc|floatformat:2|default_if_none:"0"}}</td>
                                    <td>${{employee.get_atm|floatformat:2|default_if_none:"0"}}</td>
                                    
                                    <td>${{employee.get_cash|floatformat:2|default_if_none:"0"}}</td>

                                    <td>${{employee.get_cash_usd|floatformat:2|default_if_none:"0"}}</td>
                                    
                                    <td>${{employee.get_paypal|floatformat:2|default_if_none:"0"}}</td>

                                    <td>${{employee.get_aguinaldo_mensual|floatformat:2|default_if_none:"0"}}</td>

                                    <td>${{employee.get_total_ceo|floatformat:2|default_if_none:"0"}}</td>

                                    <td>
                                        <div class="d-flex flex-row">
                                            
                                                <!-- delete BUTTON -->
                                                <a class="btn btn-danger" href="{% url 'dashboard:deleteceo' id=employee.id %}">
                                                    <i class="fa-solid fa-trash fs-7"></i>
                                        </a>                                                                                  
                                                <!-- edit BUTTON -->
                                                    <a href="{% url 'dashboard:editceo' id=employee.id %}" class="px-3 shadow-sm btn btn-secondary mx-1">
                                                        <i class="fa-solid fa-pen-to-square"></i>
                                                    </a>                                                
                                        </div>                                        
                                    </td>
                                </tr>
                                {% endfor %}
                                {%endif%}
                            </tbody>
                        </table>
                    </div>

                </div>
            </div>
                       
        </div>
    </div>
<!-- end MAIN ceo -->


<!-- START modal add ceo -->
    <div class="modal fade " id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">

                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Add a new Employee</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>       

                <form  method="post">
                {% csrf_token %} 
                    <div class="modal-body">
                    
                        <div class="form-group my-3">
                            <label class="form-label">Date</label>
                            {{ ceo_form.date_join}}
                        </div>

                        <div class="form-group my-3">
                            {{ceo_form.name}}
                        </div>      
                        
                        <div class="form-group my-3">
                            <label class="form-label">Birthday</label>
                            {{ceo_form.dob}}
                        </div>

                        <div class="accordion accordion-rounded-stylish" id="accordion-twelve">
                            <div class="accordion-item">
                                
                                <div class="accordion-header  rounded-lg" id="accord-12One" data-bs-toggle="collapse" data-bs-target="#collapse12One" aria-controls="collapse12One"   aria-expanded="true"  role="button">
                                    <span class="accordion-header-icon"></span>
                                    <span class="accordion-header-text">Contact Data</span>
                                    <span class="accordion-header-indicator"></span>
                                </div>

                                <div id="collapse12One" class="collapse accordion__body hidden" aria-labelledby="accord-12One" data-bs-parent="#accordion-twelve">
                                    <div class="accordion-body-text">
                                    
                                        <div class="form-group my-3 d-flex justify-content-between">
                                            <div class="me-3">
                                                {{ceo_form.email}} </div>                                            
                                        </div>

                                        <div class="form-group my-3">
                                            {{ceo_form.tel}}
                                        </div>
                                        
                                        <div class="form-group my-3">
                                            {{ceo_form.address}}
                                        </div>
                                        
                                    </div>
                                </div>                             
                            </div>                          
                        </div>

                        <div class="form-group my-3">
                            {{ceo_form.rol}}
                        </div>

                        <div class="form-group my-3">
                            <label class="form-label">Salary</label>

                             {{salary_form.salary}}
                        </div>


                        <div id="ceo">
                            <div class="form-group my-3">
                                <label class="form-label">MP</label>

                                    {{salary_form.mp}}
                            </div>

                            <div class="form-group my-3">
                                <label class="form-label">TC</label>

                             {{salary_form.tc}}
                            </div>

                            <div class="form-group my-3">
                                <label class="form-label">ATM</label>
    
                                 {{salary_form.atm_cash}}
                            </div>
    
                            <div class="form-group my-3">
                                <label class="form-label">CASH $</label>
    
                                 {{salary_form.cash}}
                            </div>

                            <div class="form-group my-3">
                                <label class="form-label">CASH USD</label>

                                 {{salary_form.cash_usd}}
                            </div>


                            <div class="form-group my-3">
                                <label class="form-label">PAYPAL</label>

                                 {{salary_form.paypal}}
                            </div>

                        </div>

                        <div class="form-floating my-3 text-center">
                            <button type="submit" class="shadow-sm btn btn-secondary" name="addemployee"><i class="fa-solid fa-check me-2"></i> Submit</button>
                        </div>

                    </div>
                </form>
            </div>
        </div>
    </div>
<!-- END modal add ceo -->
{% endblock %}


{% block additional_js %}

<script>
    var select = document.getElementById("rol"); 
    var option = select.querySelector('option[value="SEO"]');
    var option2 = select.querySelector('option[value="GADS"]');
    var option3 = select.querySelector('option[value="FADS"]');
    var option4 = select.querySelector('option[value="Design"]');
    var option5 = select.querySelector('option[value="Admin"]');
    var option6 = select.querySelector('option[value="Sales"]');
    var option7 = select.querySelector('option[value="Others"]');

        if (option) 
        {select.removeChild(option);}
        if (option2) 
        {select.removeChild(option2);}
        if (option3) 
        {select.removeChild(option3);}
        if (option4) 
        {select.removeChild(option4);}
        if (option5) 
        {select.removeChild(option5);}
        if (option6) 
        {select.removeChild(option6);}
        if (option7) 
        {select.removeChild(option7);}

</script>



{% endblock %}

dashboard/templates/dashboard/employees/comms.html
{% load static %}
{% if editemployee.sales %}

<div class="d-flex flex-row-reverse my-4">
    <a class="btn btn-primary light fs-4" href="{% url 'dashboard:employee_comms' id=editemployee.id %}">
        COMMs History
        <span class="btn-icon-end">
            <i class="fa-regular fa-calendar fs-3"></i>
        </span>
    </a>   
</div>

<div class="mt-4">
    <div class="table-responsive">
        <table id="example5" class="display mb-4" style="min-width: 845px">
            <thead>
                <tr>                   
                    <th>DATE</th>
                    <th>CLIENT</th>
                    <th>SALE</th>
                    <th>KIND</th>
                    <th>%</th>
                    <th>COMM</th>
                </tr>
            </thead>
            
            <tbody>
                {% for i in editemployee.get_sales_this_m.all %}
                
                <tr>

                    <td>{{i.date|date:"d/m/Y"}}</td>
                    
                    
                    <td><a href="{% url 'dashboard:editclient' id=i.client.id %}"> {{i.client}}</a></td>
                    
                    


                    <td><a href="{% url 'dashboard:editsale' id=i.id %}">{{i.service}} ${{i.change|floatformat:2}}</a></td>

                    <td>{% if i.revenue == "OneOff" %} OneOff {% else %} {% if i.kind == " - " %} New Client  {% else %}{{i.kind}} {% endif %} {% endif %}</td>


                    <td>{% if i.revenue == "OneOff" %}
                            {{comms_conf.one_off}} %
                        {% else %}
                            {% if i.kind == "Upsell" %}
                                {{comms_conf.up_sell}} %
                            {% else %}
                               {% if comms_this_m.rr_percent == 1 %} {% else %}{{comms_this_m.rr_percent}} %{% endif %}
                            {% endif %}
                        
                        {% endif %} 
                    </td>

                    <td>${{i.get_comm|floatformat:2}}</td>

                </tr>
                {% endfor %}
                
            </tbody>
        </table>
    </div>
        
</div>
{%endif%}

dashboard/templates/dashboard/employees/deleteholiday.html
<!-- Delete Client Modal -->
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
               
            <div class="modal-body text-center py-5">
                <h4 class="fs-2 my-2">Delete this holiday permanently...</h4>
                <h4 class="fs-2 my-2">¿Are you sure?</h4>

                <div class="form-floating mt-5">
                    <a href="{% url 'dashboard:employees' %}" class="btn fs-7 mx-2">
                        <i class="fa-solid fa-arrow-left me-2 fs-7"></i> Nop, go back.
                    </a>
                    <a href="{% url 'dashboard:deleteholiday' id=i.id %}" class="shadow-sm btn btn-danger fs-6 p-3">
                        <i class="fa-regular fa-trash-can fs-5 me-1"></i> Yes!
                    </a>
                </div>
            </div>

    </div>
</div>