core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
   
    #Dashboard
    path('', include('dashboard.urls', namespace='dashboard')),

    #Frontend
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from dashboard.users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.urls import path


from dashboard import dashboard_views
from dashboard.users import users_views

app_name='dashboard'

urlpatterns = [
    
    path('conf/',dashboard_views.conf, name="conf"),
    path('setting/',dashboard_views.setting, name="setting"),
    path('comms/',dashboard_views.comms, name="comms"),
    

    path('employees/',dashboard_views.employees, name="employees"),
    path('employees/export/',dashboard_views.export_employees, name="export_employees"),

    path('employees/old/', dashboard_views.employeesold, name="old"),

    path('employee/<int:id>/delete/', dashboard_views.deleteemployee, name="deleteemployee"), 
    path('employee/<int:id>/edit/', dashboard_views.editemployee, name="editemployee"),
    path('employee/<int:id>/comms/', dashboard_views.employee_comms, name="employee_comms"),

    
    path('holiday/delete/<int:id>/', dashboard_views.deleteholiday, name="deleteholiday"), 
    path('holiday/edit/<int:id>/', dashboard_views.editholiday, name="editholiday"), 



    path('ceo/',dashboard_views.ceo, name="ceo"),
    path('ceo/edit/<int:id>/', dashboard_views.editceo, name="editceo"),  
    path('ceo/delete/<int:id>/', dashboard_views.deleteceo, name="deleteceo"),  
    path('ceo/export/', dashboard_views.export_ceo, name="export_ceo"),  

    path('expenses/', dashboard_views.expenses, name="expenses"),
    path('expenses/delete/<int:id>/', dashboard_views.deleteexpense, name="deleteexpense"), 
    path('expenses/edit/<int:id>/', dashboard_views.editexpense, name="editexpense"), 
    path('expenses/deleteexpenses/', dashboard_views.delete_expenses, name="deleteexpenses"),
    path('expenses/history/<int:id>/', dashboard_views.expenseshistory, name="expenseshistory"),
    path('expenses/export/', dashboard_views.export_expenses, name="export_expenses"),

    
    path('clients/',dashboard_views.clients, name="clients"),
    path('clients/deleteclient/<int:id>/', dashboard_views.deleteclient, name="deleteclient"),
    path('clients/editclient/<int:id>/', dashboard_views.editclient, name="editclient"),
    path('clients/addclientsale/<int:id>/', dashboard_views.addclientsale, name="addclientsale"),
    path('clients/deleteclients/', dashboard_views.delete_clients, name="deleteclients"),
    path('clients/export/', dashboard_views.export_clients, name="export_clients"),
    path('clients/rr/export/', dashboard_views.export_rr, name="export_rr"),

    path('client-autocomplete/', dashboard_views.client_autocomplete, name='client_autocomplete'),

    path('adjustments/',dashboard_views.adjustment, name="adjustment"),
    path('adjustments/<int:id>/',dashboard_views.adjustment, name="adjustsale"),
    path('adjustment/<int:id>/delete/', dashboard_views.deleteadj, name="canceladj"),
    path('adjustment/<int:id>/change/', dashboard_views.editadj, name="editadj"),

    path('adj/',dashboard_views.adj, name="adj"),


    path('services/<int:id>/', dashboard_views.editservice, name="editservice"),
    path('services/<int:id>/restore/', dashboard_views.restoreservice, name="restoreservice"),




    path('cancellations/', dashboard_views.cancellations, name="cancellations"),




    path('sales/',dashboard_views.sales, name="sales"),
    path('sales/deletesale/<int:id>/', dashboard_views.deletesale, name="deletesale"),
    path('sales/editsale/<int:id>/', dashboard_views.editsale, name="editsale"),
    path('salesdata/',dashboard_views.salesdata, name="salesdata"),
    path('sales/deletesales/', dashboard_views.delete_sales, name="deletesales"),
    path('sales/export/', dashboard_views.export_sales, name='export_sales'),





    
	path('users/',users_views.users,name="users"),
	path('user-details/<int:id>/',users_views.user_details,name="user-details"),
	path('add-user/',users_views.add_user,name="add-user"),
	path('edit-user/<int:id>/',users_views.edit_user,name="edit-user"),
	path('delete-user/<int:id>/',users_views.delete_user,name="delete-user"),
	path('delete-multiple-user/',users_views.delete_multiple_user,name="delete-multiple-user"),

	path('login/',users_views.login_user,name="login"),
	path('logout/',users_views.logout_user,name="logout"),
	path('groups/',users_views.groups_list,name="groups"),
	path('group-edit/<int:id>/',users_views.group_edit,name="group-edit"),
	path('group-delete/<int:id>/',users_views.group_delete,name="group-delete"),
	path('group-add/',users_views.group_add,name="group-add"),
	path('permissions/',users_views.permissions,name="permissions"),
	path('edit-permissions/<int:id>/',users_views.edit_permissions,name="edit-permissions"),
	path('delete-permissions/<int:id>/',users_views.delete_permissions,name="delete-permissions"),
	path('assign-permissions-to-user/<int:id>/',users_views.assign_permissions_to_user,name="assign-permissions-to-user"),
	path('signup/',users_views.signup,name="signup"),
	path('activate/<uidb64>/<token>/',users_views.activate, name='activate'),


    path('',dashboard_views.index,name="index"),
    path('index/',dashboard_views.index,name="index"),
    path('activity/',dashboard_views.activity,name="activity"),
    path('page-lock-screen/',dashboard_views.page_lock_screen,name="page-lock-screen"),
    path('page-error-400/',dashboard_views.page_error_400,name="page-error-400"),
    path('page-error-403/',dashboard_views.page_error_403,name="page-error-403"),
    path('page-error-404/',dashboard_views.page_error_404,name="page-error-404"),
    path('page-error-500/',dashboard_views.page_error_500,name="page-error-500"),
    path('page-error-503/',dashboard_views.page_error_503,name="page-error-503"),


    path('', users_views.password_change, name='password_change'),






    # This Route for PasswordChange
    path('password/', users_views.password_change, name='password_change'),

    # These Routes for PasswordReset
    path('password_reset/', auth_views.PasswordResetView.as_view(
        form_class=EmailValidationOnForgotPassword,
        success_url=reverse_lazy('dashboard:password_reset_done')),name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('dashboard:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


] 

dashboard/users/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager 
from django.contrib.auth.models import Group




class CustomAccountManager(BaseUserManager):
	
	def create_superuser(self, email, username, first_name, last_name, password,**other_fields):
		other_fields.setdefault('is_staff',True)
		other_fields.setdefault('is_superuser',True)
		other_fields.setdefault('is_active',True)
		if other_fields.get('is_staff') is not True:
			raise ValueError(
				'Superuser must be assigned to is_staff=True.')
		if other_fields.get('is_superuser') is not True:
			raise ValueError(
				'Superuser must be assigned to is_superuser=True.')
		super_user = self.create_user(username,email,first_name, last_name, password, **other_fields)
		return super_user

	def create_user(self, username,email, first_name, last_name, password,**other_fields):
		if not email:
			raise ValueError(_('You must provide an email address'))
		email = self.normalize_email(email)
		user = self.model(username=username, email=email, first_name=first_name, last_name=last_name, **other_fields)
		user.set_password(password)
		user.save()
		return user


def user_directory_path(instance, filename):
	return f'users/{instance.email}/images/{filename}'

class CustomUser(AbstractBaseUser, PermissionsMixin):
	GENDER_CHOICES = (
		('','Choose gender'),
		('Male', 'Male'),
		('Female', 'Female'),
		('Others', 'Others'),
	)
	username = models.CharField(max_length=191,unique=True)
	email = models.EmailField(_('email address'),unique=True)
	first_name = models.CharField(max_length=255,blank=True)
	last_name = models.CharField(max_length=255,blank=True)
	groups = models.ManyToManyField(Group,blank=True)
	
	is_staff = models.BooleanField(default=True)
	is_active = models.BooleanField(default=True)
	
	objects = CustomAccountManager()

	USERNAME_FIELD = 'email'  
	REQUIRED_FIELDS = ['username','first_name','last_name']
	

	def __str__(self):
		return self.username

dashboard/forms.py
from django import forms
from django.forms import ModelForm, TextInput

from dashboard.models import Configurations, Comms, ConfTier

class TierConf(ModelForm):
    class Meta:
        model = ConfTier
        exclude = ['id', 'tier_v']
        
        widgets = {
            'tier_i' : TextInput(attrs={'class':"form-control",
            'id':"tier_i",
            'placeholder':"Tier I"}),
            
            'tier_ii' : TextInput(attrs={'class':"form-control",
            'id':"tier_ii",
            'placeholder':"Tier II"}),
            
            'tier_iii' : TextInput(attrs={'class':"form-control",
            'id':"tier_iii",
            'placeholder':"Tier III"}),
            
            'tier_iv' : TextInput(attrs={'class':"form-control",
            'id':"tier_iv",
            'placeholder':"Tier IV"}),
            
            
        }


class CommsForm(forms.ModelForm):
    class Meta:
        model = Comms
        exclude = ['id']
        
        widgets = {
            'rr_1' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_1",
            'placeholder':"RR I"}),
            
            'com_rr_1' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_1",
            'placeholder':"COMM RR I"}),
            
            'rr_2' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_2",
            'placeholder':"RR II"}),
            
            'com_rr_2' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_2",
            'placeholder':"COMM RR II"}),
            
            'rr_3' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_3",
            'placeholder':"RR III"}),
            
            'com_rr_3' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_3",
            'placeholder':"COMM III"}),
            
            'rr_4' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_4",
            'placeholder':"RR IV"}),
            
            'com_rr_4' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_4",
            'placeholder':"COMM RR IV"}),
            
            'rr_5' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_5",
            'placeholder':"RR V"}),
            
            'com_rr_5' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_5",
            'placeholder':"COMM RR V"}),
            
            'one_off' : forms.TextInput(attrs={'class':"form-control",
            'id':"one_off",
            'placeholder':"One Off"}),
            
            'up_sell' : forms.TextInput(attrs={'class':"form-control",
            'id':"up_sell",
            'placeholder':"Up Sell"}),         
            
        }

class UploadFileForm(forms.Form):
    file = forms.FileField()



class ConfigurationForm(forms.ModelForm):
    
    class Meta:
        model = Configurations
        fields = ( 
                  'name',
                  'value',
                  'title',
                  'description',
                  'input_type',
                  'editable',
                  'params'
                  )
                    

dashboard/users/forms.py
from django import forms
from dashboard.users.models import CustomUser
from django.contrib.auth.models import Group, Permission
from django.contrib.auth import authenticate
from django.contrib.auth.forms import PasswordResetForm


class SignupForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = CustomUser
        fields = (
                  'username',
                  'email',
                  'first_name',
                  'last_name',
                  'password1',
                  'password2',
                )
        
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


#Add User Form
class CustomUserForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(),required=False)


    class Meta:
        model = CustomUser
        fields = ( 
                  'username',
                  'email',
                  'first_name',
                  'last_name',
                  'groups',
                  'password1',
                  'password2',
                )
       
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user







class EditUserForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(),required=False)
   

    class Meta:
        model = CustomUser
        fields = (
                  'username',
                  'email',
                  'first_name',
                  'last_name',
                  
                  'groups',
                )

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save()
        return user




class LoginForm(forms.Form):
    email =  forms.EmailField()
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        return self.cleaned_data
        
    def login(self, request):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        return user
        

class EmailValidationOnForgotPassword(PasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        if not CustomUser.objects.filter(email__iexact=email, is_active=True).exists():
            raise forms.ValidationError("There is no user registered with the specified email address!")
        return email


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('name','permissions')

class PermissionsForm(forms.ModelForm):
    name = forms.CharField(label='Name', help_text="Example: Can action modelname")
    codename = forms.CharField(label='Code Name', help_text="Example: action_modelname")

    class Meta:
        model = Permission
        fields = ('name','codename','content_type')


class UserPermissionsForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('user_permissions',)

dashboard/templates/dashboard/expenses/deleteexpense.html
<!-- Delete Client Modal -->
<div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
               
            <div class="modal-body text-center py-5">
                <p class="fs-5 my-2">Deleting {{expense}}...</p>
                <h4 class="fs-2 my-2">¿Are you sure?</h4>

                <div class="form-floating mt-5">
                    <a href="/expenses/" class="btn fs-7 mx-2">
                        <i class="fa-solid fa-arrow-left me-2 fs-7"></i> Nop, go back
                    </a>
                    <a href="{% url 'dashboard:deleteexpense' id=expense.id %}" class="shadow-sm btn btn-danger fs-6 p-3">
                        <i class="fa-regular fa-trash-can fs-5 me-1"></i> Yes, delete it!
                    </a>
                </div>
            </div>

    </div>
</div>

dashboard/templates/dashboard/expenses/editexpense.html
{% extends 'dashboard/elements/layouts/admin.html' %}

{% load static %}

{% block additional_css %}
{% endblock %}

{% block content %}


<!-- delete expense modal -->
<div class="modal" id="deleteexpense{{editexpense.id}}">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
                   
                <div class="modal-body text-center py-5">
                    <p class="fs-2 my-2">Deleting {{editexpense}} permanently...</p>
                    <h4 class="fs-2 my-2">¿Are you sure?</h4>
    
                    <div class="form-floating mt-5">
                        <a href="./" class="btn fs-7 mx-2">
                            <i class="fa-solid fa-arrow-left me-2 fs-7"></i> Nop, go back.
                        </a>
                        <a href="{% url 'dashboard:deleteexpense' id=editexpense.id %}" class="shadow-sm btn btn-danger fs-6 p-3">
                            <i class="fa-regular fa-trash-can fs-5 me-1"></i> Yes!
                        </a>
                    </div>
                </div>
    
        </div>
    </div>
    
</div>

<!-- MAIN -->
        <div class="row page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item active"><a href="/expenses/"> EXPENSES </a></li>
                <li class="breadcrumb-item"><a> {{editexpense}} </a> </li>
            </ol>
        </div>

        <a href="{% url 'dashboard:expenseshistory' id=editexpense.id %}" class="flex-row-reverse mt-4 px-3 fs-4 btn btn-light"> See History </a>

        <div class="row">
            <div class="col-xl-12 col-lg-12">
                <div class="card">
                    <div class="card-header">

                        <h4 class="card-title my-3">Change</h4>

                        <div class="form-floating pt-4 my-3 d-flex flex-row-reverse">
                                                
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteexpense{{editexpense.id}}">Delete<span class="btn-icon-end">
                                <i class="fa-solid fa-trash fs-7"></i></span></button>



                        </div>

                    </div>


                    <div class="card-body mt-0 pt-0">
                        <div class="basic-form">
                            <form  method="post">
                                {% csrf_token %}
                                <div class="modal-body">
                                    <div class="pt-1 pb-4">
                                        <div class="formcontrol">                                         
                                            <div class="form-floating mb-3">
                                                <div class="form-group d-flex flex-row">
                                                    {{form.date}}
                                                </div>
                                                <div class="form-group my-3">
                                                    <div class="fs-5 ml-4">
                                                        Category
                                                    </div>
                                                    {{form.category}}
                                                </div>
                                                <div class="form-group my-3">
                                                    
                                                    {{form.concept}}
                                                </div>
                                                <div class="form-group my-3">
                                                   
                                                    {{form.value}}
                                                </div>

                                                <div class="form-group my-3">
                                                    <div class="fs-5 ml-4">
                                                        Currrency
                                                    </div>
                                                    {{form.currency}}
                                                </div>

                                                <div class="form-group my-3">
                                                    <div class="fs-5 ml-4">
                                                        WOP
                                                    </div>
                                                    {{form.wop}}
                                                </div>
                    
                                            </div>
                                        </div>       
                    
                                        
                                    </div>
                                    <div class="form-floating my-3 text-center">
                                        <button type="submit" class="shadow-sm btn btn-secondary" name="editexpense"><i class="fa-solid fa-check me-2"></i> Submit</button>
                                    </div>
                                </div>
                                </form>


                        </div>


                    </div>
                    
                </div>
                
            </div>
        </div>







{% endblock %}





{% block additional_js %}

 <!-- NEWMODAL -->
 <script>
    const deleteexpense = new bootstrap.Modal('#deleteexpense',   {keyboard: true}    )
</script>
{% endblock %}

dashboard/templates/dashboard/expenses/expenseshistory.html
{% extends 'dashboard/elements/layouts/admin.html' %}
{% load static %}

{% block content %}



        <div class="page-titles">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'dashboard:expenses' %}">Expenses</a></li>
                <li class="breadcrumb-item active"><a href="{% url 'dashboard:editexpense' id=editexpense.id %}"> {{editexpense.category}}: {{editexpense.concept}} </a></li>

            </ol>
        </div>

        <div class="row">
            <div class="col-xl-12">
                <div class="card">
                    <div class="card-body">
                        
                        <div class="mt-2">
                            <div class="table-responsive">
                                <table id="example4" class="display mb-4" style="min-width: 845px">
                                    <thead>
                                        <tr>
                                            
                                            <th>PERIOD</th>
                                            <th>VALUE</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% if same_expense %}
                                        {% for i in same_expense %}
                                        <tr>
                                            
    
                                            <td>{{i.date|date:"m/Y"}}</td>
                                            <td>{{i.value}}</td>
                                        </tr>
                                        {% endfor %}
                                        {% else %}

                                        <p>No history of this expense registered yet...</p>
                                        {% endif %}
                                       
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        


{% endblock %}