core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
   
    #Dashboard
    path('', include('dashboard.urls', namespace='dashboard')),

    #Frontend
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from dashboard.users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.urls import path


from dashboard import dashboard_views
from dashboard.users import users_views

app_name='dashboard'

urlpatterns = [
    
    path('conf/',dashboard_views.conf, name="conf"),
    path('setting/',dashboard_views.setting, name="setting"),
    path('comms/',dashboard_views.comms, name="comms"),
    

    path('employees/',dashboard_views.employees, name="employees"),
    path('employees/export/',dashboard_views.export_employees, name="export_employees"),

    path('employees/old/', dashboard_views.employeesold, name="old"),

    path('employee/<int:id>/delete/', dashboard_views.deleteemployee, name="deleteemployee"), 
    path('employee/<int:id>/edit/', dashboard_views.editemployee, name="editemployee"),
    path('employee/<int:id>/comms/', dashboard_views.employee_comms, name="employee_comms"),

    
    path('holiday/delete/<int:id>/', dashboard_views.deleteholiday, name="deleteholiday"), 
    path('holiday/edit/<int:id>/', dashboard_views.editholiday, name="editholiday"), 



    path('ceo/',dashboard_views.ceo, name="ceo"),
    path('ceo/edit/<int:id>/', dashboard_views.editceo, name="editceo"),  
    path('ceo/delete/<int:id>/', dashboard_views.deleteceo, name="deleteceo"),  
    path('ceo/export/', dashboard_views.export_ceo, name="export_ceo"),  

    path('expenses/', dashboard_views.expenses, name="expenses"),
    path('expenses/delete/<int:id>/', dashboard_views.deleteexpense, name="deleteexpense"), 
    path('expenses/edit/<int:id>/', dashboard_views.editexpense, name="editexpense"), 
    path('expenses/deleteexpenses/', dashboard_views.delete_expenses, name="deleteexpenses"),
    path('expenses/history/<int:id>/', dashboard_views.expenseshistory, name="expenseshistory"),
    path('expenses/export/', dashboard_views.export_expenses, name="export_expenses"),

    
    path('clients/',dashboard_views.clients, name="clients"),
    path('clients/deleteclient/<int:id>/', dashboard_views.deleteclient, name="deleteclient"),
    path('clients/editclient/<int:id>/', dashboard_views.editclient, name="editclient"),
    path('clients/addclientsale/<int:id>/', dashboard_views.addclientsale, name="addclientsale"),
    path('clients/deleteclients/', dashboard_views.delete_clients, name="deleteclients"),
    path('clients/export/', dashboard_views.export_clients, name="export_clients"),
    path('clients/rr/export/', dashboard_views.export_rr, name="export_rr"),

    path('client-autocomplete/', dashboard_views.client_autocomplete, name='client_autocomplete'),

    path('adjustments/',dashboard_views.adjustment, name="adjustment"),
    path('adjustments/<int:id>/',dashboard_views.adjustment, name="adjustsale"),
    path('adjustment/<int:id>/delete/', dashboard_views.deleteadj, name="canceladj"),
    path('adjustment/<int:id>/change/', dashboard_views.editadj, name="editadj"),

    path('adj/',dashboard_views.adj, name="adj"),


    path('services/<int:id>/', dashboard_views.editservice, name="editservice"),
    path('services/<int:id>/restore/', dashboard_views.restoreservice, name="restoreservice"),




    path('cancellations/', dashboard_views.cancellations, name="cancellations"),




    path('sales/',dashboard_views.sales, name="sales"),
    path('sales/deletesale/<int:id>/', dashboard_views.deletesale, name="deletesale"),
    path('sales/editsale/<int:id>/', dashboard_views.editsale, name="editsale"),
    path('salesdata/',dashboard_views.salesdata, name="salesdata"),
    path('sales/deletesales/', dashboard_views.delete_sales, name="deletesales"),
    path('sales/export/', dashboard_views.export_sales, name='export_sales'),





    
	path('users/',users_views.users,name="users"),
	path('user-details/<int:id>/',users_views.user_details,name="user-details"),
	path('add-user/',users_views.add_user,name="add-user"),
	path('edit-user/<int:id>/',users_views.edit_user,name="edit-user"),
	path('delete-user/<int:id>/',users_views.delete_user,name="delete-user"),
	path('delete-multiple-user/',users_views.delete_multiple_user,name="delete-multiple-user"),

	path('login/',users_views.login_user,name="login"),
	path('logout/',users_views.logout_user,name="logout"),
	path('groups/',users_views.groups_list,name="groups"),
	path('group-edit/<int:id>/',users_views.group_edit,name="group-edit"),
	path('group-delete/<int:id>/',users_views.group_delete,name="group-delete"),
	path('group-add/',users_views.group_add,name="group-add"),
	path('permissions/',users_views.permissions,name="permissions"),
	path('edit-permissions/<int:id>/',users_views.edit_permissions,name="edit-permissions"),
	path('delete-permissions/<int:id>/',users_views.delete_permissions,name="delete-permissions"),
	path('assign-permissions-to-user/<int:id>/',users_views.assign_permissions_to_user,name="assign-permissions-to-user"),
	path('signup/',users_views.signup,name="signup"),
	path('activate/<uidb64>/<token>/',users_views.activate, name='activate'),


    path('',dashboard_views.index,name="index"),
    path('index/',dashboard_views.index,name="index"),
    path('activity/',dashboard_views.activity,name="activity"),
    path('page-lock-screen/',dashboard_views.page_lock_screen,name="page-lock-screen"),
    path('page-error-400/',dashboard_views.page_error_400,name="page-error-400"),
    path('page-error-403/',dashboard_views.page_error_403,name="page-error-403"),
    path('page-error-404/',dashboard_views.page_error_404,name="page-error-404"),
    path('page-error-500/',dashboard_views.page_error_500,name="page-error-500"),
    path('page-error-503/',dashboard_views.page_error_503,name="page-error-503"),


    path('', users_views.password_change, name='password_change'),






    # This Route for PasswordChange
    path('password/', users_views.password_change, name='password_change'),

    # These Routes for PasswordReset
    path('password_reset/', auth_views.PasswordResetView.as_view(
        form_class=EmailValidationOnForgotPassword,
        success_url=reverse_lazy('dashboard:password_reset_done')),name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('dashboard:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


] 

dashboard/users/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager 
from django.contrib.auth.models import Group




class CustomAccountManager(BaseUserManager):
	
	def create_superuser(self, email, username, first_name, last_name, password,**other_fields):
		other_fields.setdefault('is_staff',True)
		other_fields.setdefault('is_superuser',True)
		other_fields.setdefault('is_active',True)
		if other_fields.get('is_staff') is not True:
			raise ValueError(
				'Superuser must be assigned to is_staff=True.')
		if other_fields.get('is_superuser') is not True:
			raise ValueError(
				'Superuser must be assigned to is_superuser=True.')
		super_user = self.create_user(username,email,first_name, last_name, password, **other_fields)
		return super_user

	def create_user(self, username,email, first_name, last_name, password,**other_fields):
		if not email:
			raise ValueError(_('You must provide an email address'))
		email = self.normalize_email(email)
		user = self.model(username=username, email=email, first_name=first_name, last_name=last_name, **other_fields)
		user.set_password(password)
		user.save()
		return user


def user_directory_path(instance, filename):
	return f'users/{instance.email}/images/{filename}'

class CustomUser(AbstractBaseUser, PermissionsMixin):
	GENDER_CHOICES = (
		('','Choose gender'),
		('Male', 'Male'),
		('Female', 'Female'),
		('Others', 'Others'),
	)
	username = models.CharField(max_length=191,unique=True)
	email = models.EmailField(_('email address'),unique=True)
	first_name = models.CharField(max_length=255,blank=True)
	last_name = models.CharField(max_length=255,blank=True)
	groups = models.ManyToManyField(Group,blank=True)
	
	is_staff = models.BooleanField(default=True)
	is_active = models.BooleanField(default=True)
	
	objects = CustomAccountManager()

	USERNAME_FIELD = 'email'  
	REQUIRED_FIELDS = ['username','first_name','last_name']
	

	def __str__(self):
		return self.username

dashboard/forms.py
from django import forms
from django.forms import ModelForm, TextInput

from dashboard.models import Configurations, Comms, ConfTier

class TierConf(ModelForm):
    class Meta:
        model = ConfTier
        exclude = ['id', 'tier_v']
        
        widgets = {
            'tier_i' : TextInput(attrs={'class':"form-control",
            'id':"tier_i",
            'placeholder':"Tier I"}),
            
            'tier_ii' : TextInput(attrs={'class':"form-control",
            'id':"tier_ii",
            'placeholder':"Tier II"}),
            
            'tier_iii' : TextInput(attrs={'class':"form-control",
            'id':"tier_iii",
            'placeholder':"Tier III"}),
            
            'tier_iv' : TextInput(attrs={'class':"form-control",
            'id':"tier_iv",
            'placeholder':"Tier IV"}),
            
            
        }


class CommsForm(forms.ModelForm):
    class Meta:
        model = Comms
        exclude = ['id']
        
        widgets = {
            'rr_1' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_1",
            'placeholder':"RR I"}),
            
            'com_rr_1' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_1",
            'placeholder':"COMM RR I"}),
            
            'rr_2' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_2",
            'placeholder':"RR II"}),
            
            'com_rr_2' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_2",
            'placeholder':"COMM RR II"}),
            
            'rr_3' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_3",
            'placeholder':"RR III"}),
            
            'com_rr_3' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_3",
            'placeholder':"COMM III"}),
            
            'rr_4' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_4",
            'placeholder':"RR IV"}),
            
            'com_rr_4' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_4",
            'placeholder':"COMM RR IV"}),
            
            'rr_5' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_5",
            'placeholder':"RR V"}),
            
            'com_rr_5' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_5",
            'placeholder':"COMM RR V"}),
            
            'one_off' : forms.TextInput(attrs={'class':"form-control",
            'id':"one_off",
            'placeholder':"One Off"}),
            
            'up_sell' : forms.TextInput(attrs={'class':"form-control",
            'id':"up_sell",
            'placeholder':"Up Sell"}),         
            
        }

class UploadFileForm(forms.Form):
    file = forms.FileField()



class ConfigurationForm(forms.ModelForm):
    
    class Meta:
        model = Configurations
        fields = ( 
                  'name',
                  'value',
                  'title',
                  'description',
                  'input_type',
                  'editable',
                  'params'
                  )
                    

dashboard/users/forms.py
from django import forms
from dashboard.users.models import CustomUser
from django.contrib.auth.models import Group, Permission
from django.contrib.auth import authenticate
from django.contrib.auth.forms import PasswordResetForm


class SignupForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = CustomUser
        fields = (
                  'username',
                  'email',
                  'first_name',
                  'last_name',
                  'password1',
                  'password2',
                )
        
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


#Add User Form
class CustomUserForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(),required=False)


    class Meta:
        model = CustomUser
        fields = ( 
                  'username',
                  'email',
                  'first_name',
                  'last_name',
                  'groups',
                  'password1',
                  'password2',
                )
       
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user







class EditUserForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(),required=False)
   

    class Meta:
        model = CustomUser
        fields = (
                  'username',
                  'email',
                  'first_name',
                  'last_name',
                  
                  'groups',
                )

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save()
        return user




class LoginForm(forms.Form):
    email =  forms.EmailField()
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        return self.cleaned_data
        
    def login(self, request):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        return user
        

class EmailValidationOnForgotPassword(PasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        if not CustomUser.objects.filter(email__iexact=email, is_active=True).exists():
            raise forms.ValidationError("There is no user registered with the specified email address!")
        return email


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('name','permissions')

class PermissionsForm(forms.ModelForm):
    name = forms.CharField(label='Name', help_text="Example: Can action modelname")
    codename = forms.CharField(label='Code Name', help_text="Example: action_modelname")

    class Meta:
        model = Permission
        fields = ('name','codename','content_type')


class UserPermissionsForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('user_permissions',)

dashboard/templates/dashboard/modules/group-list.html
{% extends 'dashboard/elements/layouts/admin.html' %}
{% load static widget_tweaks %}


{% block additional_css %}
 
{% endblock %}


{% block message %}
{% include 'dashboard/elements/alert.html' %}
{% endblock %}


{% block content %}

    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Manage Groups </h4>
                {% if perms.auth.add_group %}
                <a href="{% url 'dashboard:group-add' %}" class="btn btn-primary content-justify-right">ADD GROUP  <span class="btn-icon-end">
                    <i class="fa fa-plus"></i></span>
                </a>
                {% endif %}


            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-responsive-md ck-table">
                        <thead>
                            <tr>
                                
                                <th scope="col">Group Name</th>
                                <th scope="col">User Count</th>
                                <th scope="col">Perms Count</th>
                                {% if perms.auth.change_group or perms.auth.delete_group %}
                                <th scope="col">Action</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            
                            {% for group in groups %}
                            
                            <tr>

                               

                                <td>{{ group.name }}</td>

                                <td>
                                    <span class={% if group.user_count == 0 %}
                                    "badge badge-{{ colors.dark }}"
                                    {% elif group.user_count > 0 and group.user_count < 10  %}
                                    "badge badge-{{ colors.primary }}"
                                    {% elif group.user_count >= 10 %}
                                    "badge badge-{{ colors.success }}"
                                    {% endif %}><i class="fa fa-users" aria-hidden="true"></i> &nbsp;{{ group.user_count }}</span>
                                </td>

                                

                                 <td>
                                    
                                    
                                    <span class={% if group.perms_count == 0 %}
                                    "badge badge-{{ colors.dark }}"
                                    {% elif group.perms_count > 0 and group.perms_count < 10  %}
                                    "badge badge-{{ colors.primary }}"
                                    {% elif group.perms_count >= 10 %}
                                    "badge badge-{{ colors.success }}"
                                    {% endif %}><i class="fa fa-lock" aria-hidden="true"></i> &nbsp;{{ group.perms_count }}</span> 
                                </td>

                                {% if perms.auth.change_group or perms.auth.delete_group %}
                                <td>
                                    <span class="sweetalert">

                                        {% if perms.auth.change_group %}

                                        <a href="{% url 'dashboard:group-edit' id=group.id %}"class="btn btn-primary shadow btn-xs sharp me-1" data-bs-toggle="tooltip"
                                            data-placement="top" title="Edit">
                                            <i class="fas fa-pencil-alt"></i>
                                        </a>
                                        {% endif %}
                                        {% if perms.auth.delete_group %}
                                        <a href="{% url 'dashboard:group-delete' id=group.id %}" class="btn btn-danger shadow btn-xs sharp sweet-success-cancel" data-bs-toggle="tooltip"
                                            data-placement="top" title="Delete"><i class="fa fa-trash"></i>
                                        </a>
                                        {% endif %}
                                    </span>
                                </td>

                                {% endif %}
                            </tr>
                           
                            
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


{% endblock %}


{% block additional_js %}
<script>
    $('.sweet-success-cancel').on('click', function (event) {
           event.preventDefault();
           const url = $(this).attr('href');
   
           Swal.fire({
               title: 'Are you sure?',
               text: "You won't be able to revert this!",
               type: "warning",
               icon: 'question',
               showCancelButton: true,
               confirmButtonText: "Yes, delete it !!",
               confirmButtonText: 'Delete',
               confirmButtonColor: "#DD6B55"
               
           }).then((result) => {
               if (result.value) {
                   window.location.href = url;
               } else if (result.dismiss === Swal.DismissReason.cancel) {
                   event.preventDefault();
               }
           })
       });
   </script>
   
{% endblock %}

dashboard/templates/dashboard/modules/users.html
{% extends 'dashboard/elements/layouts/admin.html' %}
{% load static %}


{% block additional_css %}
 
{% endblock %}



{% block message %}
{% include 'dashboard/elements/alert.html' %}
{% endblock %}


{% block content %}

<div id="message">
</div>  

        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Users</h4>
                    
                    <div class="d-flex">

                       

                        {% if perms.users.add_customuser %}
                        <a href="{% url 'dashboard:add-user' %}" class="btn btn-primary">ADD USER <span class="btn-icon-end">
                            <i class="fa fa-plus"></i></span>
                        </a>
                        {% endif %}

                    </div>

                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-responsive-md">
                            <thead>
                                <tr>
                                   
                                   
                                    <th>Full Name</th>
                                    <th>Email</th>
                                    <th>Status</th>
                                    


                                    {% if perms.users.delete_customuser or perms.users.change_customuser or perms.auth.change_permission %}
                                    <th>Action</th>
                                    {% endif %}


                                   
                                </tr>
                            </thead>
                            <tbody>
                                {% csrf_token %}
                                {% for user in user_list %}
                                <tr id="{{ user.id }}">
                                 

                                    <td>
                                        <a href="{% url 'dashboard:edit-user' id=user.id %}">
                                        <div class="d-flex align-items-center">
                                            <span class="w-space-no">{{ user.first_name }} {{ user.last_name }}</span>
                                        </div>
                                    </a>
                                    </td>
                                    <td><strong>{{ user.email }}</strong></td>

                                    
                                    <td>
                                        <div class="d-flex align-items-center">
                                            {% if user.is_active %}
                                            <i class="fa fa-circle text-success me-1"></i> 
                                            {% else %} 
                                            <i class="fa fa-circle text-dark me-1"></i> 

                                            {% endif %}
                                        </div>
                                    
                                    </td>
                                    <td>
                                        <div class="sweetalert">
                                            <div class="d-flex">
                                                
                                                {% if perms.users.change_customuser %}
                                                <a href="{% url 'dashboard:edit-user' id=user.id %}" class="btn btn-primary shadow btn-xs sharp me-1" title="Edit"><i class="fa fa-pencil"></i></a>
                                                {% endif %}
                                                {% if perms.users.delete_customuser %}
                                                <a href="{% url 'dashboard:delete-user' id=user.id %}" class="btn btn-danger shadow btn-xs sharp sweet-success-cancel" title="Delete"><i class="fa fa-trash"></i></a>
                                                {% endif %}
                                            </div>
                                    </div>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>

                        <div class="text-primary d-flex justify-content-center">
						{% if message  %}
                            <h4>{{message}}</h4>
						{% endif  %}
                        </div>
                    </div>

                    {% if not message  %}
                    <nav mt-5 class="d-flex align-items-center justify-content-between pt-3">

                        <p>
                            <span class="current">
                            Page {{ user_list.number }} of {{ user_list.paginator.num_pages }}.
                           </span> 
                           </p>
                           

                        <ul class="pagination pagination-gutter">
                            
                                <li class="page-item page-indicator ">
                                    <a class="page-link" href="{% if user_list.has_previous %}
                                                                ?page={{ user_list.previous_page_number }}
                                                                {% else %}
                                                                javascript:void(0);
                                                                {% endif %}">
                                        <i class="la la-angle-left"></i></a>
                                </li>

                            {% for i in user_list.paginator.page_range|slice:":3" %}

                                <li class="page-item {% if user_list.number == i %}
                                                    active{% endif %}"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                            
                            {% endfor %}

                            
                            {% if user_list.number > 3 %}
                            <li class="page-item active"><a class="page-link" href="?page={{ user_list.number }}">{{ user_list.number }}</a></li>
                            {% endif %}
                            
                            <li class="page-item page-indicator ">
                                <a class="page-link"  href="{% if user_list.has_next %}
                                                            ?page={{ user_list.next_page_number }}
                                                            {% else %}
                                                            javascript:void(0);
                                                            {% endif %}">
                                    <i class="la la-angle-right"></i></a>
                            </li>
                            <li>

                              

                            </li>
                        </ul>
                       
                    </nav>
                    {% endif %}
                </div>
            </div>
        </div>


{% endblock %}


{% block additional_js %}

   
{% endblock %}