core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
   
    #Dashboard
    path('', include('dashboard.urls', namespace='dashboard')),

    #Frontend
    path('ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dashboard/urls.py
from dashboard.users.forms import EmailValidationOnForgotPassword
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from django.urls import path


from dashboard import dashboard_views
from dashboard.users import users_views

app_name='dashboard'

urlpatterns = [
    
    path('conf/',dashboard_views.conf, name="conf"),
    path('setting/',dashboard_views.setting, name="setting"),
    path('comms/',dashboard_views.comms, name="comms"),
    

    path('employees/',dashboard_views.employees, name="employees"),
    path('employees/export/',dashboard_views.export_employees, name="export_employees"),

    path('employees/old/', dashboard_views.employeesold, name="old"),

    path('employee/<int:id>/delete/', dashboard_views.deleteemployee, name="deleteemployee"), 
    path('employee/<int:id>/edit/', dashboard_views.editemployee, name="editemployee"),
    path('employee/<int:id>/comms/', dashboard_views.employee_comms, name="employee_comms"),

    
    path('holiday/delete/<int:id>/', dashboard_views.deleteholiday, name="deleteholiday"), 
    path('holiday/edit/<int:id>/', dashboard_views.editholiday, name="editholiday"), 



    path('ceo/',dashboard_views.ceo, name="ceo"),
    path('ceo/edit/<int:id>/', dashboard_views.editceo, name="editceo"),  
    path('ceo/delete/<int:id>/', dashboard_views.deleteceo, name="deleteceo"),  
    path('ceo/export/', dashboard_views.export_ceo, name="export_ceo"),  

    path('expenses/', dashboard_views.expenses, name="expenses"),
    path('expenses/delete/<int:id>/', dashboard_views.deleteexpense, name="deleteexpense"), 
    path('expenses/edit/<int:id>/', dashboard_views.editexpense, name="editexpense"), 
    path('expenses/deleteexpenses/', dashboard_views.delete_expenses, name="deleteexpenses"),
    path('expenses/history/<int:id>/', dashboard_views.expenseshistory, name="expenseshistory"),
    path('expenses/export/', dashboard_views.export_expenses, name="export_expenses"),

    
    path('clients/',dashboard_views.clients, name="clients"),
    path('clients/deleteclient/<int:id>/', dashboard_views.deleteclient, name="deleteclient"),
    path('clients/editclient/<int:id>/', dashboard_views.editclient, name="editclient"),
    path('clients/addclientsale/<int:id>/', dashboard_views.addclientsale, name="addclientsale"),
    path('clients/deleteclients/', dashboard_views.delete_clients, name="deleteclients"),
    path('clients/export/', dashboard_views.export_clients, name="export_clients"),
    path('clients/rr/export/', dashboard_views.export_rr, name="export_rr"),

    path('client-autocomplete/', dashboard_views.client_autocomplete, name='client_autocomplete'),

    path('adjustments/',dashboard_views.adjustment, name="adjustment"),
    path('adjustments/<int:id>/',dashboard_views.adjustment, name="adjustsale"),
    path('adjustment/<int:id>/delete/', dashboard_views.deleteadj, name="canceladj"),
    path('adjustment/<int:id>/change/', dashboard_views.editadj, name="editadj"),

    path('adj/',dashboard_views.adj, name="adj"),


    path('services/<int:id>/', dashboard_views.editservice, name="editservice"),
    path('services/<int:id>/restore/', dashboard_views.restoreservice, name="restoreservice"),




    path('cancellations/', dashboard_views.cancellations, name="cancellations"),




    path('sales/',dashboard_views.sales, name="sales"),
    path('sales/deletesale/<int:id>/', dashboard_views.deletesale, name="deletesale"),
    path('sales/editsale/<int:id>/', dashboard_views.editsale, name="editsale"),
    path('salesdata/',dashboard_views.salesdata, name="salesdata"),
    path('sales/deletesales/', dashboard_views.delete_sales, name="deletesales"),
    path('sales/export/', dashboard_views.export_sales, name='export_sales'),





    
	path('users/',users_views.users,name="users"),
	path('user-details/<int:id>/',users_views.user_details,name="user-details"),
	path('add-user/',users_views.add_user,name="add-user"),
	path('edit-user/<int:id>/',users_views.edit_user,name="edit-user"),
	path('delete-user/<int:id>/',users_views.delete_user,name="delete-user"),
	path('delete-multiple-user/',users_views.delete_multiple_user,name="delete-multiple-user"),

	path('login/',users_views.login_user,name="login"),
	path('logout/',users_views.logout_user,name="logout"),
	path('groups/',users_views.groups_list,name="groups"),
	path('group-edit/<int:id>/',users_views.group_edit,name="group-edit"),
	path('group-delete/<int:id>/',users_views.group_delete,name="group-delete"),
	path('group-add/',users_views.group_add,name="group-add"),
	path('permissions/',users_views.permissions,name="permissions"),
	path('edit-permissions/<int:id>/',users_views.edit_permissions,name="edit-permissions"),
	path('delete-permissions/<int:id>/',users_views.delete_permissions,name="delete-permissions"),
	path('assign-permissions-to-user/<int:id>/',users_views.assign_permissions_to_user,name="assign-permissions-to-user"),
	path('signup/',users_views.signup,name="signup"),
	path('activate/<uidb64>/<token>/',users_views.activate, name='activate'),


    path('',dashboard_views.index,name="index"),
    path('index/',dashboard_views.index,name="index"),
    path('activity/',dashboard_views.activity,name="activity"),
    path('page-lock-screen/',dashboard_views.page_lock_screen,name="page-lock-screen"),
    path('page-error-400/',dashboard_views.page_error_400,name="page-error-400"),
    path('page-error-403/',dashboard_views.page_error_403,name="page-error-403"),
    path('page-error-404/',dashboard_views.page_error_404,name="page-error-404"),
    path('page-error-500/',dashboard_views.page_error_500,name="page-error-500"),
    path('page-error-503/',dashboard_views.page_error_503,name="page-error-503"),


    path('', users_views.password_change, name='password_change'),






    # This Route for PasswordChange
    path('password/', users_views.password_change, name='password_change'),

    # These Routes for PasswordReset
    path('password_reset/', auth_views.PasswordResetView.as_view(
        form_class=EmailValidationOnForgotPassword,
        success_url=reverse_lazy('dashboard:password_reset_done')),name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy('dashboard:password_reset_complete')), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


] 

dashboard/users/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager 
from django.contrib.auth.models import Group




class CustomAccountManager(BaseUserManager):
	
	def create_superuser(self, email, username, first_name, last_name, password,**other_fields):
		other_fields.setdefault('is_staff',True)
		other_fields.setdefault('is_superuser',True)
		other_fields.setdefault('is_active',True)
		if other_fields.get('is_staff') is not True:
			raise ValueError(
				'Superuser must be assigned to is_staff=True.')
		if other_fields.get('is_superuser') is not True:
			raise ValueError(
				'Superuser must be assigned to is_superuser=True.')
		super_user = self.create_user(username,email,first_name, last_name, password, **other_fields)
		return super_user

	def create_user(self, username,email, first_name, last_name, password,**other_fields):
		if not email:
			raise ValueError(_('You must provide an email address'))
		email = self.normalize_email(email)
		user = self.model(username=username, email=email, first_name=first_name, last_name=last_name, **other_fields)
		user.set_password(password)
		user.save()
		return user


def user_directory_path(instance, filename):
	return f'users/{instance.email}/images/{filename}'

class CustomUser(AbstractBaseUser, PermissionsMixin):
	GENDER_CHOICES = (
		('','Choose gender'),
		('Male', 'Male'),
		('Female', 'Female'),
		('Others', 'Others'),
	)
	username = models.CharField(max_length=191,unique=True)
	email = models.EmailField(_('email address'),unique=True)
	first_name = models.CharField(max_length=255,blank=True)
	last_name = models.CharField(max_length=255,blank=True)
	groups = models.ManyToManyField(Group,blank=True)
	
	is_staff = models.BooleanField(default=True)
	is_active = models.BooleanField(default=True)
	
	objects = CustomAccountManager()

	USERNAME_FIELD = 'email'  
	REQUIRED_FIELDS = ['username','first_name','last_name']
	

	def __str__(self):
		return self.username

dashboard/forms.py
from django import forms
from django.forms import ModelForm, TextInput

from dashboard.models import Configurations, Comms, ConfTier

class TierConf(ModelForm):
    class Meta:
        model = ConfTier
        exclude = ['id', 'tier_v']
        
        widgets = {
            'tier_i' : TextInput(attrs={'class':"form-control",
            'id':"tier_i",
            'placeholder':"Tier I"}),
            
            'tier_ii' : TextInput(attrs={'class':"form-control",
            'id':"tier_ii",
            'placeholder':"Tier II"}),
            
            'tier_iii' : TextInput(attrs={'class':"form-control",
            'id':"tier_iii",
            'placeholder':"Tier III"}),
            
            'tier_iv' : TextInput(attrs={'class':"form-control",
            'id':"tier_iv",
            'placeholder':"Tier IV"}),
            
            
        }


class CommsForm(forms.ModelForm):
    class Meta:
        model = Comms
        exclude = ['id']
        
        widgets = {
            'rr_1' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_1",
            'placeholder':"RR I"}),
            
            'com_rr_1' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_1",
            'placeholder':"COMM RR I"}),
            
            'rr_2' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_2",
            'placeholder':"RR II"}),
            
            'com_rr_2' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_2",
            'placeholder':"COMM RR II"}),
            
            'rr_3' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_3",
            'placeholder':"RR III"}),
            
            'com_rr_3' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_3",
            'placeholder':"COMM III"}),
            
            'rr_4' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_4",
            'placeholder':"RR IV"}),
            
            'com_rr_4' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_4",
            'placeholder':"COMM RR IV"}),
            
            'rr_5' : forms.TextInput(attrs={'class':"form-control",
            'id':"rr_5",
            'placeholder':"RR V"}),
            
            'com_rr_5' : forms.TextInput(attrs={'class':"form-control",
            'id':"com_rr_5",
            'placeholder':"COMM RR V"}),
            
            'one_off' : forms.TextInput(attrs={'class':"form-control",
            'id':"one_off",
            'placeholder':"One Off"}),
            
            'up_sell' : forms.TextInput(attrs={'class':"form-control",
            'id':"up_sell",
            'placeholder':"Up Sell"}),         
            
        }

class UploadFileForm(forms.Form):
    file = forms.FileField()



class ConfigurationForm(forms.ModelForm):
    
    class Meta:
        model = Configurations
        fields = ( 
                  'name',
                  'value',
                  'title',
                  'description',
                  'input_type',
                  'editable',
                  'params'
                  )
                    

dashboard/users/forms.py
from django import forms
from dashboard.users.models import CustomUser
from django.contrib.auth.models import Group, Permission
from django.contrib.auth import authenticate
from django.contrib.auth.forms import PasswordResetForm


class SignupForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    class Meta:
        model = CustomUser
        fields = (
                  'username',
                  'email',
                  'first_name',
                  'last_name',
                  'password1',
                  'password2',
                )
        
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


#Add User Form
class CustomUserForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(),required=False)


    class Meta:
        model = CustomUser
        fields = ( 
                  'username',
                  'email',
                  'first_name',
                  'last_name',
                  'groups',
                  'password1',
                  'password2',
                )
       
    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user







class EditUserForm(forms.ModelForm):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)

    groups = forms.ModelMultipleChoiceField(queryset=Group.objects.all(),required=False)
   

    class Meta:
        model = CustomUser
        fields = (
                  'username',
                  'email',
                  'first_name',
                  'last_name',
                  
                  'groups',
                )

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save()
        return user




class LoginForm(forms.Form):
    email =  forms.EmailField()
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        if not user or not user.is_active:
            raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
        return self.cleaned_data
        
    def login(self, request):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        user = authenticate(email=email, password=password)
        return user
        

class EmailValidationOnForgotPassword(PasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        if not CustomUser.objects.filter(email__iexact=email, is_active=True).exists():
            raise forms.ValidationError("There is no user registered with the specified email address!")
        return email


class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = ('name','permissions')

class PermissionsForm(forms.ModelForm):
    name = forms.CharField(label='Name', help_text="Example: Can action modelname")
    codename = forms.CharField(label='Code Name', help_text="Example: action_modelname")

    class Meta:
        model = Permission
        fields = ('name','codename','content_type')


class UserPermissionsForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('user_permissions',)

dashboard/templates/dashboard/activity.html
{% extends 'dashboard/elements/layouts/admin.html' %}

{% load static %}

{% block additional_css %}

{% endblock %}

{% block content %}

        <div class="card">
            <div class="card-body pt-0">
                <div class="widget-timeline style-3 ">
                    <ul id="loglist" class="timeline-active my-4">
                        {% for e in list %}
                        <li class="d-flex aligns-baseline ">
                            {% if e.get_event_type_display %}
                            <h4 class="font-w400 time">{{e.datetime}}</h4>
                            <div class="panel">
                                <a class="timeline-panel text-muted d-flex aligns-center">
                                    {% if e.get_event_type_display == "Update" %} <div class="badge badge-xl badge-warning fs-6"> <i class="fa-solid fa-pen-to-square"></i> </div>
                                        {% elif e.get_event_type_display == "Create" %} <div class="badge badge-xl badge-secondary fs-6"><i class="fa fa-plus"></i> </div>
                                        {% elif e.get_event_type_display == "Delete" %} <div class="badge badge-xl badge-primary fs-6"> <i class="fa-solid fa-trash fs-7"></i> </div>
                                        {% endif %}
                                    <h4 class="mb-0"><strong> {{e.user}} </strong> {{e.get_event_type_display}} {{e.content_type.model}} 
                                        {% if e.get_event_type_display == "Update" %} <strong class="text-warning"> {{e.object_repr}}</strong>
                                        {% elif e.get_event_type_display == "Create" %} <strong class="text-secondary"> {{e.object_repr}}</strong>
                                        {% elif e.get_event_type_display == "Delete" %} <strong class="text-primary"> {{e.object_repr}}</strong>
                                        {% endif %}                                        
                                    </h4>
                                </a>                                
                            </div>
                            {% else %}
                            <h4 class="font-w400 time">{{e.datetime}}</h4>
                            <div class="panel">
                                <a class="timeline-panel text-muted d-flex aligns-center">
                                    {% if e.get_login_type_display == "Login" %} <div class="badge badge-xl badge-secondary fs-6"> <i class="fa-solid fa-right-to-bracket"></i></div>
                                    {% elif e.get_login_type_display == "Logout" %} <div class="badge badge-xl badge-primary fs-6"> <i class="fa-solid fa-right-to-bracket fa-flip-horizontal"></i> </div>
                                    {% endif %}
                                    <h4 class="mb-0"><strong> {{e.user}} </strong> {{e.get_login_type_display}}                             
                                    </h4>
                                </a>                                
                            </div>	
                            {%endif%}	
                        </li>
                        {% endfor %}
                    </ul>
                </div>

                <nav mt-5 class="d-flex align-items-center justify-content-between pt-3">

                    <p>
                      <span class="current">
                    Page {{ list.number }} of {{ list.paginator.num_pages }}.
                      </span> 
                    </p>

                    <ul class="pagination pagination-gutter  justify-content-end">
                        
                      <li class="page-item page-indicator ">
                          <a class="page-link" href="{% if list.has_previous %}
                        ?page={{ list.previous_page_number }}
                                      {% else %}
                                   javascript:void(0);
                                     {% endif %}">
                              <i class="la la-angle-left"></i></a>
                      </li>

                  {% for i in list.paginator.page_range|slice:":3" %}

                      <li class="page-item {% if list.number == i %}
                                          active{% endif %}"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                  
                  {% endfor %}

                  
                  {% if list.number > 3 %}
                  <li class="page-item active"><a class="page-link" href="?page={{ list.number }}">{{ list.number }}</a></li>
                  {% endif %}
                  
                  <li class="page-item page-indicator ">
                      <a class="page-link"  href="{% if list.has_next %}
                                                  ?page={{ list.next_page_number }}
                                                  {% else %}
                                                  javascript:void(0);
                                                  {% endif %}">
                          <i class="la la-angle-right"></i></a>
                  </li>

              </ul>
                  </nav>
                  
            </div>
        </div>	


	
{% endblock %}

{% block additional_js %}
    
    
{% endblock %}

dashboard/templates/dashboard/commsconf.html
{% extends 'dashboard/elements/layouts/admin.html' %}

{% load static %}

{% block additional_css %}
{% endblock %}

{% block content %}


        
<!-- COMMS CONF -->

    <div class="row">

           
                <div class="col-xl-10 m-auto">
                    <div class="card">
                        <div class="card-body">
                            <form  method="post">  
                                {% csrf_token %}
                                <div class="basic-list-group">

                                    <ul class="list-group list-group-flush">

                                        <li class="list-group-item d-flex justify-content-between align-items-center my-3 flex-row-reverse">
                                            <h2 class="me-2"> %</h2>

                                            <div class="col-lg-3"> {{form.com_rr_1}}</div>
                                            <h4 class="me-5"> :</h4>                                            

                                            <div class="col-lg-6"> {{form.rr_1}}</div>
                                            <h4 class="ms-5"> $</h4>                                            

                                            <h2 class="me-2">> </h2> 
                                            <h4 class="me-4"> SALE RR </h4>                                            
                                        </li>

                                        <li class="list-group-item d-flex justify-content-between align-items-center my-3 flex-row-reverse">
                                            <h2 class="me-2"> %</h2>

                                            <div class="col-lg-3"> {{form.com_rr_2}}</div>
                                            <h4 class="me-5"> :</h4>                                            

                                            <div class="col-lg-6"> {{form.rr_2}}</div>
                                            <h4 class="ms-5"> $</h4>                                            

                                            <h2 class="me-2">> </h2> 
                                            <h4 class="me-4"> SALE RR </h4>                                            
                                        </li>

                                        
                                        <li class="list-group-item d-flex justify-content-between align-items-center my-3 flex-row-reverse">
                                            <h2 class="me-2"> %</h2>

                                            <div class="col-lg-3"> {{form.com_rr_3}}</div>
                                            <h4 class="me-5"> :</h4>                                            

                                            <div class="col-lg-6"> {{form.rr_3}}</div>
                                            <h4 class="ms-5"> $</h4>                                            

                                            <h2 class="me-2">> </h2> 
                                            <h4 class="me-4"> SALE RR </h4>                                            
                                        </li>

                                        
                                        <li class="list-group-item d-flex justify-content-between align-items-center my-3 flex-row-reverse">
                                            <h2 class="me-2"> %</h2>

                                            <div class="col-lg-3"> {{form.com_rr_4}}</div>
                                            <h4 class="me-5"> :</h4>                                            

                                            <div class="col-lg-6"> {{form.rr_4}}</div>
                                            <h4 class="ms-5"> $</h4>                                            

                                            <h2 class="me-2">> </h2> 
                                            <h4 class="me-4"> SALE RR </h4>                                            
                                        </li>

                                        
                                        <li class="list-group-item d-flex justify-content-between align-items-center my-3 flex-row-reverse">
                                            <h2 class="me-2"> %</h2>

                                            <div class="col-lg-3"> {{form.com_rr_5}}</div>
                                            <h4 class="me-5"> :</h4>                                            

                                            <div class="col-lg-6"> {{form.rr_5}}</div>
                                            <h4 class="ms-5"> $</h4>                                            

                                            <h2 class="me-2">> </h2> 
                                            <h4 class="me-4"> SALE RR </h4>                                            
                                        </li>


                                        <li class="list-group-item d-flex justify-content-between align-items-center my-3 flex-row-reverse">
                                            <h2 class="me-2"> %</h2>
                                            <div class="col-lg-9"> {{form.up_sell}}</div>
                                            <h4 class="me-5"> Upsell:</h4>    
                                        </li>

                                        <li class="list-group-item d-flex justify-content-between align-items-center my-3 flex-row-reverse">
                                            <h2 class="me-2"> %</h2>
                                            <div class="col-lg-9"> {{form.one_off}}</div>
                                            <h4 class="me-5"> One Off:</h4>    
                                        </li>

                                    </ul>

                                </div>

                                <div class="form-floating my-5 d-flex flex-row m-auto col-md-6">
                                    <button type="submit" class="shadow-sm btn btn-secondary px-5" name="edittier"><i class="fa-solid fa-check me-2"></i> Save new Settings</button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>                      


    </div>
<!-- END COMMS CONF -->


{% endblock %}

{% block additional_js %}

{% endblock %}

dashboard/templates/dashboard/email_adjust_account_template.html
<p> [ {{adj.client.name}} {{adj.client.admin_email}} {{adj.notice_date}} ]</p>
<br>
<p>Estimado cliente, </p>
<p>El motivo de este email es para comunicarte un ajuste por inflación.</p>
<br>
{% if services|length > 1 %}
    <p> Servicios: </p>
    {% for s in services %}
        <p> - {{s.service}} </p>
    {% endfor %}
{% endif %}
<br>
<p>Inversión actual: ${{adj.old_value|floatformat:2}}</p>
<p>Inversión con ajuste: ${{adj.new_value|floatformat:2}}</p>
<p>Ajuste: ${{adj.dif|floatformat:2}}</p>
<br>
<p>El ajuste se hará en el próximo pago{% if services|length == 1 %}{% for s in services %} de {{s.service}}{% endfor %}{% endif %}.</p>
<p>Cualquier duda no dejes de consultarnos.</p>
<p>Saludos,</p>
<br>
<p>Imactions</p>
<p>www.imactions.agency</p>

dashboard/templates/dashboard/settings.html
{% extends 'dashboard/elements/layouts/admin.html' %}

{% load static %}

{% block additional_css %}
{% endblock %}

{% block content %}


        
<!-- TIER CONF -->

    <div class="row">
        <div class="col-12">

           
            <div class="card">

                <div class="d-flex flex-row">

                    {% if perms.users.add_customuser %}

                    <div class="d-flex  m-4">

                            <a href="{% url 'dashboard:users' %}" class="btn btn-primary fs-3"> CHANGE USERS  <span><i class="fa-solid fa-users-gear mx-3 fs-3"></i></span>
                            </a>
                    </div>

                    {% endif %}

                    <div class="d-flex  m-4">

                        <a href="{% url 'dashboard:conf' %}" class="btn btn-secondary fs-3"> CHANGE TIER  <span><i class="fa-solid fa-gear mx-3"></i></span>
                        </a>
                    </div>


                    <div class="d-flex  m-4">

                        <a href="{% url 'dashboard:comms' %}" class="btn btn-info fs-3"> CHANGE COMMs  <span>
                            <i class="fa-solid fa-comments-dollar mx-3"></i>

                        </span>
                        </a>
                    </div>



                </div>

            </div>
        </div>            
    </div>
<!-- END TIER CONF -->


{% endblock %}

{% block additional_js %}

{% endblock %}